# Slayer Configuration
misc:
    join_message: true
    private_scoreboard: true
    level_up_firework: true

# Updating
update:
    auto: false
    notify: true

# Tasks
tasks:
    limit: 5
    full_list: true
    join_reminders: true
    completion_firework: true
    point_multiplier: 1.0
    reusable: false

# Forfeit Handling
forfeit:
    enable: true
    punish: true

# Expiration Handling
expiration:
    punish: true

# Blocking
block:
    spawner_kills: true

# Data Related
data:
    sqlite:
        use: true
        database: slayer #This should be untouched 99% of the time.
    mysql:
        use: false
        host: localhost
        port: 3306
        database: ''
        user: ''
        pass: ''

    save_freq: 300 #seconds
    assignment_refresh_freq: 120 #seconds
    entity_tracking_period: 1200 #seconds
