# Slayer Configuration
misc:
    join_message: true

# Updating
update:
    auto: true
    notify: true

# Restrictions
tasks:
    limit: 5
    full_list: true
    join_reminders: true
    completion_firework: true

# Forfeit Handling
forfeit:
    enable: true
    punish: true

# Expiration Handling
expiration:
    punish: true

# Blocking
block:
    spawner_kills: true

# Data Related
data:
    save_freq: 300 #seconds
    assignment_refresh_freq: 120 #seconds
    entity_tracking_period: 1200 #seconds