name: Slayer
main: net.alexben.Slayer.Slayer
version: 0.1
author: _Alex
commands:
    sl:
        usage: /sl
        permission: slayer.basic
    slayer:
        usage: /slayer
        permission: slayer.basic
    sladmin:
        usage: /sladmin
        permission: slayer.admin
permissions:
    slayer.basic:
        description: The default permission for players.
        default: true
    slayer.admin:
        description: The administration permission node.
        default: false
