name: Slayer
main: net.alexben.Slayer.Slayer
version: 1.1.1
author: _Alex
commands:
    sl:
        usage: /sl
    slayer:
        usage: /slayer
    sladmin:
        usage: /sladmin
permissions:
    slayer.basic:
        description: The default permission for players.
        default: true
    slayer.admin:
        description: The administration permission node.
        default: op
    slayer.update:
        description: Allows the player to perform an auto update of the plugin.
        default: op
